controller_site/controller_site/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("monitor/", include("monitor.urls")),
    path('admin/', admin.site.urls),
]

controller_site/monitor/urls.py
from django.urls import path

from . import views


app_name = 'monitor'
urlpatterns = [
    path("", views.index, name="index"),
    path('create/', views.created_task, name='create_task')
]

controller_site/monitor/models.py
from django.db import models


class ListJobs(models.Model):
    active = models.BooleanField(default=True)

    workshop_number = models.IntegerField()  # номер цеха
    creation_date = models.DateTimeField()  # дата
    name_model = models.CharField(max_length=200)  # имя модели
    name_order = models.CharField(max_length=200)  # имя заказа
    name_operation = models.CharField(max_length=200)  # имя операции
    number_operation = models.IntegerField()  # номер операции
    name_work_center_name = models.CharField(max_length=200)  # название рабочего центра
    full_name_of_the_workers = models.CharField(max_length=200)  # ФИО рабочих исполнителей

    @classmethod
    def create(cls, dct):
        list_jobs = cls(
            workshop_number=dct['workshop_number'],
            creation_date=dct['creation_date'],
            name_model=dct['name_model'],
            name_order=dct['name_order'],
            name_operation=dct['name_operation'],
            number_operation=dct['number_operation'],
            name_work_center_name=dct['name_work_center_name'],
            full_name_of_the_workers=dct['full_name_of_the_workers']
        )
        return list_jobs


class ListCompletedJobs(models.Model):

    workshop_number = models.IntegerField()  # номер цеха
    creation_date = models.DateTimeField()  # дата
    name_model = models.CharField(max_length=200)  # имя модели
    name_order = models.CharField(max_length=200)  # имя заказа
    name_operation = models.CharField(max_length=200)  # имя операции
    number_operation = models.IntegerField()  # номер операции
    name_work_center_name = models.CharField(max_length=200)  # название рабочего центра
    Full_name_of_the_workers = models.CharField(max_length=200)  # ФИО рабочих исполнителей
    time_of_the_master_call = models.DateTimeField()  # время вызова мастера
    time_of_the_controller_call = models.DateTimeField()  # время вызова контролёра
    full_name_of_the_master_who_called = models.CharField(max_length=200)  # ФИО вызвавшего мастера
    full_name_of_the_responding_controller = models.CharField(max_length=200)  # ФИО ответившего контролёра
    time_of_the_controller_response = models.DateTimeField() # время ответа контролёра
    # full_name_of_the_responding_controller = models.CharField(max_length=200) # ФИО ответившего контролёра
    full_name_of_the_controller_who_made_the_decision = models.CharField(max_length=200, null=True)  # ФИО принявшего решение контролёра
    time_of_the_controller_decision = models.DateTimeField() # время принятия решения контролёром
    CHOICES_SOLUTION = {
        'waiting for the controller': 'waiting for the controller',
        'accepted': 'accepted',
        'not accepted': 'not accepted',
        'defective': 'defective'
    }
    solution = models.CharField(max_length=200, choices=CHOICES_SOLUTION)  # статус сменного задания (решение)

controller_site/monitor/views.py
from django.shortcuts import render, get_object_or_404, get_list_or_404
from django.http import HttpResponse, Http404, HttpResponseRedirect
from django.urls import reverse
from django.template import loader
from .models import ListJobs
import datetime as dt


def index(request):
    active_tasks = ListJobs.objects.filter(active=True)
    completed_tasks = []
    print(str(request.POST))

    ls = [
        'workshop_number',
        'name_model',
        'name_order',
        'name_operation',
        'number_operation',
        'name_work_center_name',
        'full_name_of_the_workers'
    ]
    if 'workshop_number' in request.POST.keys() and request.POST['workshop_number']:
        dct = {elem: request.POST[elem] for elem in ls}
        dct['creation_date'] = dt.datetime.strptime(request.POST['creation_date_0'] + request.POST['creation_date_1']
                                                    , '%Y-%m-%d%M:%S')
        ListJobs.objects.get_or_create(
            workshop_number=dct['workshop_number'],
            creation_date=dct['creation_date'],
            name_model=dct['name_model'],
            name_order=dct['name_order'],
            name_operation=dct['name_operation'],
            number_operation=dct['number_operation'],
            name_work_center_name=dct['name_work_center_name'],
            full_name_of_the_workers=dct['full_name_of_the_workers']
        )

    return render(request, 'monitor/index.html',
                  {"active_tasks": active_tasks, 'completed_tasks': completed_tasks})


def created_task(request):
    return render(request, 'monitor/created_task.html')

controller_site/monitor/templates/monitor/created_task.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<form action="{% url 'monitor:index' %}" method="post">
    {% csrf_token %}
    <fieldset>
        <p><label class="required">номер:  </label><input type="number" required id="id_workshop_number" name="workshop_number"></p>
        <p><label class="required">дата:  </label><input type="date" name="creation_date_0" size="10" required id="id_creation_date_0"></p>
        <p><label class="required">время:  </label><input type="time" name="creation_date_1" size="8" required id="id_creation_date_1"></p>
        <p><label class="required">имя модели:  </label><input type="text" maxlength="200" name="name_model" id="id_name_model"></p>
        <p><label class="required">имя заказа:  </label><input type="text" maxlength="200" name="name_order" id="id_name_order"></p>
        <p><label class="required">имя операции:  </label><input type="text" maxlength="200" name="name_operation" id="id_name_operation"></p>
        <p><label class="required">номер операции:  </label><input type="number" name="number_operation" id="id_number_operation"></p>
        <p><label class="required">название рабочего центра:  </label><input type="text" maxlength="200" name="name_work_center_name" id="id_name_work_center_name"></p>
        <p><label class="required">ФИО рабочих исполнителей:  </label><input type="text" maxlength="200" name="full_name_of_the_workers" id="id_full_name_of_the_workers"></p>
        <p><button type='submit'>создать</button></p>
    </fieldset>
</form>

</body>
</html>

controller_site/monitor/templates/monitor/index.html
<div>
    <h3>Список активных заданий</h3>
    {% if active_tasks %}
        <ul>
            {% for task in active_tasks %}
            <li>
                <details>
                    <summary>{{ task.name_order }}</summary>
                    <ul>
                        <li> номер цеха:	{{ task.workshop_number }} </li>
                        <li> дата:    {{ task.creation_date }} </li>
                        <li> имя модели:    {{ task.name_model }} </li>
                        <li> имя заказа:    {{ task.name_order }} </li>
                        <li> имя операции:   {{ task.name_operation }} </li>
                        <li> номер операции:   {{ task.number_operation }} </li>
                        <li> название рабочего центра:   {{ task.name_work_center_name }} </li>
                        <li> ФИО рабочих исполнителей:    {{ task.full_name_of_the_workers }} </li>
                    </ul>
                    <input type="button" value="вызвать мастера" />
                    <input type="button" value="вызвать контролёра" />
                </details>
            </li>
            {% endfor %}
        </ul>
    {% else %}
        <p>not active tasks</p>
    {% endif %}

    {% if completed_tasks %}
        <h3>Список недавно выполненных заданий</h3>
        <ul>
            {% for task in completed_tasks %}
            <li>
                <details>
                    <summary>{{ task.name_order }}</summary>
                    <ul>
                        <li> номер цеха:	{{ task.workshop_number }} </li>
                        <li> дата:    {{ task.creation_date }} </li>
                        <li> имя модели:    {{ task.name_model }} </li>
                        <li> имя заказа:    {{ task.name_order }} </li>
                        <li> имя операции:   {{ task.name_operation }} </li>
                        <li> номер операции:   {{ task.number_operation }} </li>
                        <li> название рабочего центра:   {{ task.name_work_center_name }} </li>
                        <li> ФИО рабочих исполнителей:    {{ task.full_name_of_the_workers }} </li>
                    </ul>
                    <input type="button" value="вызвать мастера" />
                    <input type="button" value="вызвать контролёра" />
                </details>
            </li>
            {% endfor %}
        </ul>
    {% endif %}
    <form action="{% url 'monitor:create_task' %}">
        <input type="submit" value="создать новое задание" name="save" id="id_save"/>
    </form>

</div>